export const COUNTRIES: { code: string; name: string; flag: string; eu: boolean }[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', eu: false },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', eu: false },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱', eu: false },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿', eu: false },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪', eu: true },
  { code: 'AD', name: 'Andorre', flag: '🇦🇩', eu: false },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', eu: false },
  { code: 'AG', name: 'Antigua-et-Barbuda', flag: '🇦🇬', eu: false },
  { code: 'SA', name: 'Arabie Saoudite', flag: '🇸🇦', eu: false },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷', eu: false },
  { code: 'AM', name: 'Arménie', flag: '🇦🇲', eu: false },
  { code: 'AU', name: 'Australie', flag: '🇦🇺', eu: false },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹', eu: true },
  { code: 'AZ', name: 'Azerbaïdjan', flag: '🇦🇿', eu: false },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', eu: false },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭', eu: false },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', eu: false },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧', eu: false },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', eu: true },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', eu: false },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯', eu: false },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹', eu: false },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾', eu: false },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴', eu: false },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', eu: false },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', eu: false },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷', eu: false },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', eu: false },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬', eu: true },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', eu: false },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', eu: false },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭', eu: false },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲', eu: false },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', eu: false },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻', eu: false },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫', eu: false },
  { code: 'CL', name: 'Chili', flag: '🇨🇱', eu: false },
  { code: 'CN', name: 'Chine', flag: '🇨🇳', eu: false },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾', eu: true },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴', eu: false },
  { code: 'KM', name: 'Comores', flag: '🇰🇲', eu: false },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', eu: false },
  { code: 'CD', name: 'Congo (RDC)', flag: '🇨🇩', eu: false },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵', eu: false },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷', eu: false },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', eu: false },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', eu: false },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷', eu: true },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', eu: false },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰', eu: true },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', eu: false },
  { code: 'DM', name: 'Dominique', flag: '🇩🇲', eu: false },
  { code: 'DO', name: 'République dominicaine', flag: '🇩🇴', eu: false },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬', eu: false },
  { code: 'AE', name: 'Émirats Arabes Unis', flag: '🇦🇪', eu: false },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨', eu: false },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷', eu: false },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸', eu: true },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪', eu: true },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', eu: false },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹', eu: false },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯', eu: false },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮', eu: true },
  { code: 'FR', name: 'France', flag: '🇫🇷', eu: true },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', eu: false },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲', eu: false },
  { code: 'GE', name: 'Géorgie', flag: '🇬🇪', eu: false },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', eu: false },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷', eu: true },
  { code: 'GD', name: 'Grenade', flag: '🇬🇩', eu: false },
  { code: 'GF', name: 'Guyane française', flag: '🇬🇫', eu: false },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', eu: false },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', eu: false },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳', eu: false },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼', eu: false },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', eu: false },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', eu: false },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹', eu: false },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', eu: false },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', eu: false },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺', eu: true },
  { code: 'MH', name: 'Îles Marshall', flag: '🇲🇭', eu: false },
  { code: 'SB', name: 'Îles Salomon', flag: '🇸🇧', eu: false },
  { code: 'IN', name: 'Inde', flag: '🇮🇳', eu: false },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩', eu: false },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', eu: false },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', eu: false },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪', eu: true },
  { code: 'IS', name: 'Islande', flag: '🇮🇸', eu: false },
  { code: 'IL', name: 'Israël', flag: '🇮🇱', eu: false },
  { code: 'IT', name: 'Italie', flag: '🇮🇹', eu: true },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲', eu: false },
  { code: 'JP', name: 'Japon', flag: '🇯🇵', eu: false },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴', eu: false },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', eu: false },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', eu: false },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬', eu: false },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', eu: false },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰', eu: false },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼', eu: false },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', eu: false },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', eu: false },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻', eu: true },
  { code: 'LB', name: 'Liban', flag: '🇱🇧', eu: false },
  { code: 'LR', name: 'Libéria', flag: '🇱🇷', eu: false },
  { code: 'LY', name: 'Libye', flag: '🇱🇾', eu: false },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', eu: false },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹', eu: true },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', eu: true },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', eu: false },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', eu: false },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', eu: false },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾', eu: false },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', eu: false },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', eu: false },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', eu: false },
  { code: 'MT', name: 'Malte', flag: '🇲🇹', eu: true },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦', eu: false },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶', eu: false },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺', eu: false },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷', eu: false },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', eu: false },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽', eu: false },
  { code: 'FM', name: 'Micronésie', flag: '🇫🇲', eu: false },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩', eu: false },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', eu: false },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳', eu: false },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪', eu: false },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', eu: false },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', eu: false },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦', eu: false },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', eu: false },
  { code: 'NP', name: 'Népal', flag: '🇳🇵', eu: false },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', eu: false },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', eu: false },
  { code: 'NG', name: 'Nigéria', flag: '🇳🇬', eu: false },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴', eu: false },
  { code: 'NC', name: 'Nouvelle-Calédonie', flag: '🇳🇨', eu: false },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', eu: false },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', eu: false },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬', eu: false },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', eu: false },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', eu: false },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼', eu: false },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', eu: false },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', eu: false },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', eu: false },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', eu: false },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱', eu: true },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪', eu: false },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', eu: false },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱', eu: true },
  { code: 'PF', name: 'Polynésie française', flag: '🇵🇫', eu: false },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', eu: true },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', eu: false },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪', eu: false },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴', eu: true },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', eu: false },
  { code: 'RU', name: 'Russie', flag: '🇷🇺', eu: false },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', eu: false },
  { code: 'KN', name: 'Saint-Kitts-et-Nevis', flag: '🇰🇳', eu: false },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲', eu: false },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨', eu: false },
  { code: 'LC', name: 'Sainte-Lucie', flag: '🇱🇨', eu: false },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', eu: false },
  { code: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹', eu: false },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', eu: false },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸', eu: false },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', eu: false },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', eu: false },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬', eu: false },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰', eu: true },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮', eu: true },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴', eu: false },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩', eu: false },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', eu: false },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', eu: false },
  { code: 'SE', name: 'Suède', flag: '🇸🇪', eu: true },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', eu: false },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', eu: false },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾', eu: false },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', eu: false },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼', eu: false },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', eu: false },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', eu: false },
  { code: 'CZ', name: 'Tchéquie', flag: '🇨🇿', eu: true },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭', eu: false },
  { code: 'TL', name: 'Timor oriental', flag: '🇹🇱', eu: false },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', eu: false },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', eu: false },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹', eu: false },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳', eu: false },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲', eu: false },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷', eu: false },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', eu: false },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', eu: false },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', eu: false },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸', eu: false },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', eu: false },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', eu: false },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', eu: false },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪', eu: false },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲', eu: false },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', eu: false },
].sort((a, b) => a.name.localeCompare(b.name, 'fr'))

export const EU_CODES = new Set(['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE'])
export const isEU = (code: string) => EU_CODES.has(code)
export const countryFlag = (code: string) => COUNTRIES.find(c => c.code === code)?.flag ?? '🌍'
export const countryName = (code: string) => COUNTRIES.find(c => c.code === code)?.name ?? code
