-- =============================================================
-- CMS SEED V2 — All modules, EN as source language
-- =============================================================

-- Set EN as default language
UPDATE languages SET is_default = false WHERE code = 'fr';
UPDATE languages SET is_default = true  WHERE code = 'en';

-- =============================================================
-- INSERT LABELS
-- =============================================================

INSERT INTO cms_labels (namespace, key, description) VALUES

-- common (additions to existing)
('common','sign_out','Sign out button in sidebar'),
('common','saving','Saving state on buttons'),
('common','uploading','Upload in progress state'),
('common','type','Type field label'),
('common','role','Role field label'),
('common','first_name','First name field'),
('common','last_name','Last name field'),
('common','postal_code','Postal code field'),
('common','street','Street address field'),
('common','contact','Contact field/section'),
('common','contacts','Contacts section header'),
('common','description','Description field'),
('common','amount','Amount field'),
('common','payment_terms','Payment terms field'),
('common','mobile','Mobile phone field'),
('common','vat_number','VAT number field'),
('common','all','All filter option'),
('common','creating','Creating... loading state'),
('common','approve','Approve action'),
('common','reject','Reject action'),
('common','select','Select placeholder'),

-- clients
('clients','page_title','Clients page h1'),
('clients','add_client','Add client button'),
('clients','new_client','New client form title'),
('clients','edit_client','Edit client form title'),
('clients','search_placeholder','Client search input placeholder'),
('clients','no_clients','Empty state message'),
('clients','legal_name','Legal name field label'),
('clients','trading_name','Trading name field label'),
('clients','client_type','Client type field label'),
('clients','type_distributor','Distributor type option'),
('clients','type_private','Private client type option'),
('clients','internal_owner','Internal owner field'),
('clients','price_list','Price list field'),
('clients','general_information','General Information card header'),
('clients','commercial_terms','Commercial Terms card header'),
('clients','compliance','Compliance & Stock Rules card header'),
('clients','vat_number','VAT Number field'),
('clients','excise_number','Excise Number field'),
('clients','european_client','European client checkbox label'),
('clients','portal_access','Portal Access card header'),
('clients','portal_not_invited','Portal not invited status'),
('clients','portal_invited','Portal invited status'),
('clients','portal_active','Portal active status'),
('clients','portal_disabled','Portal disabled status'),
('clients','no_contacts','No contacts yet empty state'),
('clients','no_addresses','No addresses yet empty state'),
('clients','media','Media card header'),
('clients','logo','Logo upload label'),
('clients','photo','Photo upload label'),
('clients','status_lead','Lead status'),
('clients','status_active','Active status'),
('clients','status_inactive','Inactive status'),
('clients','status_dying','Dying status'),
('clients','status_closed','Closed status'),
('clients','modification_requests','Modification Requests section'),
('clients','approve_all','Approve all button'),

-- orders
('orders','page_title','Orders page h1'),
('orders','new_order','New Order button'),
('orders','search_placeholder','Order search placeholder'),
('orders','no_orders','Empty state'),
('orders','show_cancelled','Show cancelled orders toggle'),
('orders','hide_cancelled','Hide cancelled orders toggle'),
('orders','select_doc_type','Select document type subtitle'),
('orders','col_order_number','Order number column header'),
('orders','col_customer','Customer column header'),
('orders','col_warehouse','Warehouse column header'),
('orders','col_status','Status column header'),
('orders','col_date','Date column header'),
('orders','col_total','Total column header'),
('orders','col_po_number','PO number column header'),
('orders','status_draft','Draft order status'),
('orders','status_submitted','Submitted to client status'),
('orders','status_in_preparation','In preparation status'),
('orders','status_ready','Ready for shipment status'),
('orders','status_shipped','Shipped status'),
('orders','status_completed','Completed status'),
('orders','status_cancelled','Cancelled status'),
('orders','status_pending_approval','Pending approval status'),
('orders','status_rejected','Rejected status'),
('orders','status_approved','Approved status'),
('orders','add_product','Add product to order button'),
('orders','search_products','Search products in order placeholder'),
('orders','shipment_date','Shipment date field'),
('orders','select_customer','Select customer placeholder'),
('orders','summary','Order summary section'),
('orders','rejection_reason','Rejection reason label'),

-- purchase_orders
('purchase_orders','page_title','Purchase Orders page h1'),
('purchase_orders','new_po','New PO button'),
('purchase_orders','no_purchase_orders','Empty state'),
('purchase_orders','col_po_number','PO Number column'),
('purchase_orders','col_partner','Partner column'),
('purchase_orders','col_delivery','Delivery date column'),
('purchase_orders','col_total','Total column'),
('purchase_orders','status_draft','Draft status'),
('purchase_orders','status_sent','Sent status'),
('purchase_orders','status_confirmed','Confirmed status'),
('purchase_orders','status_received','Received status'),
('purchase_orders','status_cancelled','Cancelled status'),

-- products
('products','page_title','Products page h1'),
('products','add_product','Add Product button'),
('products','search_placeholder','Product search placeholder'),
('products','no_products','Empty state'),
('products','col_sku','SKU column'),
('products','col_product','Product name column'),
('products','col_brand','Brand column'),
('products','col_vitola','Vitola column'),
('products','col_units_pack','Units per pack column'),
('products','col_role','Role column'),
('products','role_original','Original role'),
('products','role_aged','Aged role'),
('products','role_sample','Sample role'),
('products','role_foc','FOC role'),
('products','filter_brands','Brands filter'),
('products','general_information','General Information card'),
('products','product_details','Product Details card'),

-- inventory
('inventory','page_title','Inventory page h1'),
('inventory','stock_movements','Stock Movements tab'),
('inventory','add_stock','Add Stock button'),
('inventory','search_placeholder','Inventory search placeholder'),
('inventory','no_records','Empty state'),
('inventory','col_sku','SKU column'),
('inventory','col_product','Product column'),
('inventory','col_brand','Brand column'),
('inventory','col_total','Total column'),
('inventory','select_product','Select product placeholder'),
('inventory','label_packs','Packs field label'),
('inventory','label_units','Units field label'),
('inventory','label_warehouse','Warehouse field label'),

-- finance
('finance','expenses_title','Expenses page h1'),
('finance','new_expense','New Expense button'),
('finance','tab_all_expenses','All Expenses tab'),
('finance','tab_claims','Expense Claims tab'),
('finance','no_expenses','Empty state'),
('finance','to_reimburse','To reimburse label'),
('finance','mark_as_paid','Mark as Paid button'),
('finance','col_date','Date column'),
('finance','col_vendor','Vendor column'),
('finance','col_category','Category column'),
('finance','col_amount','Amount column'),
('finance','col_receipt','Receipt column'),
('finance','scan_receipt','Scan Receipt button'),
('finance','field_date','Date field label'),
('finance','field_category','Category field label'),
('finance','field_vendor','Vendor / Payee field label'),
('finance','field_description','Description field label'),
('finance','field_amount','Amount field label'),
('finance','field_payment_method','Payment Method field label'),
('finance','add_expense','Add Expense button'),
('finance','status_pending','Pending status'),
('finance','status_approved','Approved status'),
('finance','status_posted','Posted status'),
('finance','status_rejected','Rejected status'),
('finance','status_paid','Paid status'),
('finance','status_submitted','Submitted status'),
('finance','cat_office','Office & Admin category'),
('finance','cat_travel','Travel & Entertainment category'),
('finance','cat_meals','Meals & Beverages category'),
('finance','cat_utilities','Utilities category'),
('finance','cat_professional','Professional Fees category'),
('finance','cat_marketing','Marketing & Events category'),
('finance','cat_rent','Rent category'),
('finance','cat_bank_charges','Bank Charges category'),
('finance','cat_freight','Freight & Logistics category'),
('finance','cat_other','Other category'),

-- retailers
('retailers','page_title','Retailers page title'),
('retailers','add_retailer','Add retailer button'),
('retailers','add_contact','Add contact button'),
('retailers','tab_retailers','Retailers tab'),
('retailers','tab_b2c','B2C Contacts tab'),
('retailers','tab_map','Map tab'),
('retailers','search_placeholder','Retailer search placeholder'),
('retailers','no_retailers','Empty state for retailers'),
('retailers','no_b2c','Empty state for B2C contacts'),
('retailers','form_add_title','Add Retailer form title'),
('retailers','form_edit_title','Edit Retailer form title'),
('retailers','retailer_name','Retailer Name field'),
('retailers','retailer_information','Retailer Information card'),
('retailers','photos_section','Photos section header'),
('retailers','add_photo','Add photo button'),
('retailers','no_photos','No photos yet empty state'),
('retailers','visit_notes_placeholder','Visit notes placeholder'),
('retailers','add_b2c_title','Add B2C Contact form title'),
('retailers','edit_b2c_title','Edit Contact form title'),
('retailers','linked_retailer','Linked Retailer field'),
('retailers','event_occasion','Event / Occasion field'),
('retailers','b2c_col_name','Name column header'),
('retailers','b2c_col_country','Country column header'),
('retailers','b2c_col_contact','Contact column header'),
('retailers','b2c_col_event','Event column header'),
('retailers','b2c_col_retailer','Retailer column header'),

-- partners
('partners','page_title','Partners page h1'),
('partners','add_partner','Add Partner button'),
('partners','search_placeholder','Partner search placeholder'),
('partners','no_partners','Empty state'),
('partners','filter_all_types','All Types filter'),
('partners','type_supplier','Supplier type'),
('partners','type_agent','Agent type'),
('partners','type_broker','Broker type'),
('partners','col_name','Name column'),
('partners','col_type','Type column'),
('partners','col_contact','Contact column'),
('partners','col_country','Country column'),
('partners','col_payment_terms','Payment Terms column'),
('partners','col_status','Status column'),
('partners','general_information','General Information card'),
('partners','commercial_terms','Commercial Terms card'),

-- price_lists
('price_lists','page_title','Price Lists page h1'),
('price_lists','search_placeholder','Price list search placeholder'),
('price_lists','no_entries','No price entries empty state'),
('price_lists','col_sku','SKU column'),
('price_lists','col_product','Product column'),
('price_lists','edit_hint','Tap any price field to edit hint'),

-- documents
('documents','page_title','Documents page h1'),
('documents','add_external','Add External Document button'),
('documents','file_label','File label field'),
('documents','no_folders','No folders empty state'),
('documents','no_documents','No documents empty state'),
('documents','total_folders','Total Folders stat'),
('documents','total_files','Total Files stat'),

-- reports
('reports','page_title','Reports page h1'),
('reports','tab_overview','Overview tab'),
('reports','tab_geography','Geography tab'),
('reports','tab_products','Products tab'),
('reports','tab_clients','Clients tab'),
('reports','tab_activity','Activity tab'),
('reports','kpi_revenue','Revenue KPI label'),
('reports','kpi_units_shipped','Units shipped KPI label'),
('reports','kpi_active_clients','Active clients KPI label'),
('reports','col_region','Region column'),
('reports','col_clients','Clients column'),
('reports','col_revenue','Revenue column'),
('reports','col_units','Units column'),
('reports','col_orders','Orders column'),
('reports','health_active','Active client health'),
('reports','health_at_risk','At risk client health'),
('reports','health_dormant','Dormant client health'),
('reports','health_lost','Lost client health'),
('reports','never_ordered','Never ordered label'),

-- targets
('targets','page_title','Financial Targets h1'),
('targets','subtitle','Set annual objectives subtitle'),
('targets','col_distributor','Distributor column'),
('targets','col_standard','Standard target column'),
('targets','col_push','Push target column'),
('targets','col_stretch','Stretch target column'),
('targets','col_progress','Progress column'),
('targets','no_target','No target label'),
('targets','status_urgent','Urgent status'),
('targets','status_late','Late status'),
('targets','status_good','Good status'),
('targets','status_excellent','Excellent status'),
('targets','status_amazing','Amazing status'),

-- tracking
('tracking','page_title','Tracking Log h1'),
('tracking','subtitle','Audit trail subtitle'),
('tracking','search_placeholder','Search placeholder'),
('tracking','no_events','No events empty state'),
('tracking','stat_today','Events today stat'),
('tracking','stat_users','Active users stat'),
('tracking','stat_admin','Admin actions stat'),
('tracking','stat_client','Client actions stat'),

-- settings
('settings','page_title','Settings page h1'),
('settings','language_title','Language section title'),
('settings','language_description','Language selector description'),
('settings','language_saved','Language saved confirmation'),

-- cms
('cms','page_title','CMS page h1'),
('cms','labels_count','Labels count subtitle'),
('cms','new_label','New label button'),
('cms','col_key','Key column header'),
('cms','col_description','Description column header'),
('cms','col_translation','Translation column header'),
('cms','col_status','Status column header'),
('cms','no_labels','No labels in namespace empty state'),
('cms','no_translation_placeholder','No translation placeholder text'),
('cms','auto_translate','Auto-translate button'),
('cms','translated_result','Auto-translate result message'),
('cms','create','Create button in new label form'),
('cms','label_namespace','Namespace field label'),
('cms','label_key','Key field label'),
('cms','label_description','Description field label')

ON CONFLICT (namespace, key) DO NOTHING;

-- =============================================================
-- SEED EN TRANSLATIONS
-- =============================================================

INSERT INTO cms_translations (label_id, lang_code, value)
SELECT l.id, 'en', v.val
FROM cms_labels l
JOIN (VALUES
  -- common additions
  ('common','sign_out','Sign out'),
  ('common','saving','Saving...'),
  ('common','uploading','Uploading...'),
  ('common','type','Type'),
  ('common','role','Role'),
  ('common','first_name','First Name'),
  ('common','last_name','Last Name'),
  ('common','postal_code','Postal Code'),
  ('common','street','Street'),
  ('common','contact','Contact'),
  ('common','contacts','Contacts'),
  ('common','description','Description'),
  ('common','amount','Amount'),
  ('common','payment_terms','Payment Terms'),
  ('common','mobile','Mobile'),
  ('common','vat_number','VAT Number'),
  ('common','all','All'),
  ('common','creating','Creating...'),
  ('common','approve','Approve'),
  ('common','reject','Reject'),
  ('common','select','Select...'),
  -- clients
  ('clients','page_title','Clients'),
  ('clients','add_client','Add Client'),
  ('clients','new_client','New Client'),
  ('clients','edit_client','Edit Client'),
  ('clients','search_placeholder','Search name, country...'),
  ('clients','no_clients','No clients found'),
  ('clients','legal_name','Legal Name'),
  ('clients','trading_name','Trading Name'),
  ('clients','client_type','Client Type'),
  ('clients','type_distributor','Distributor'),
  ('clients','type_private','Private'),
  ('clients','internal_owner','Internal Owner'),
  ('clients','price_list','Price List'),
  ('clients','general_information','General Information'),
  ('clients','commercial_terms','Commercial Terms'),
  ('clients','compliance','Compliance & Stock Rules'),
  ('clients','vat_number','VAT Number'),
  ('clients','excise_number','Excise Number'),
  ('clients','european_client','European client (EU member state)'),
  ('clients','portal_access','Portal Access'),
  ('clients','portal_not_invited','Not invited'),
  ('clients','portal_invited','Invited'),
  ('clients','portal_active','Active'),
  ('clients','portal_disabled','Disabled'),
  ('clients','no_contacts','No contacts yet'),
  ('clients','no_addresses','No addresses yet'),
  ('clients','media','Media'),
  ('clients','logo','Logo'),
  ('clients','photo','Photo'),
  ('clients','status_lead','Lead'),
  ('clients','status_active','Active'),
  ('clients','status_inactive','Inactive'),
  ('clients','status_dying','Dying'),
  ('clients','status_closed','Closed'),
  ('clients','modification_requests','Modification Requests'),
  ('clients','approve_all','Approve all'),
  -- orders
  ('orders','page_title','Orders'),
  ('orders','new_order','New Order'),
  ('orders','search_placeholder','Search order or customer...'),
  ('orders','no_orders','No orders found'),
  ('orders','show_cancelled','Show cancelled orders'),
  ('orders','hide_cancelled','Hide cancelled orders'),
  ('orders','select_doc_type','Select document type below'),
  ('orders','col_order_number','Order #'),
  ('orders','col_customer','Customer'),
  ('orders','col_warehouse','Warehouse'),
  ('orders','col_status','Status'),
  ('orders','col_date','Date'),
  ('orders','col_total','Total'),
  ('orders','col_po_number','PO #'),
  ('orders','status_draft','draft'),
  ('orders','status_submitted','submitted to client'),
  ('orders','status_in_preparation','in preparation'),
  ('orders','status_ready','ready for shipment'),
  ('orders','status_shipped','shipped'),
  ('orders','status_completed','completed'),
  ('orders','status_cancelled','cancelled'),
  ('orders','status_pending_approval','pending approval'),
  ('orders','status_rejected','rejected'),
  ('orders','status_approved','approved'),
  ('orders','add_product','Add Product'),
  ('orders','search_products','Search products...'),
  ('orders','shipment_date','Shipment Date'),
  ('orders','select_customer','Select customer...'),
  ('orders','summary','Summary'),
  ('orders','rejection_reason','Rejection reason:'),
  -- purchase_orders
  ('purchase_orders','page_title','Purchase Orders'),
  ('purchase_orders','new_po','New PO'),
  ('purchase_orders','no_purchase_orders','No purchase orders yet.'),
  ('purchase_orders','col_po_number','PO Number'),
  ('purchase_orders','col_partner','Partner'),
  ('purchase_orders','col_delivery','Delivery'),
  ('purchase_orders','col_total','Total'),
  ('purchase_orders','status_draft','Draft'),
  ('purchase_orders','status_sent','Sent'),
  ('purchase_orders','status_confirmed','Confirmed'),
  ('purchase_orders','status_received','Received'),
  ('purchase_orders','status_cancelled','Cancelled'),
  -- products
  ('products','page_title','Products'),
  ('products','add_product','Add Product'),
  ('products','search_placeholder','Search SKU, name, brand, Fixmer, EU-CEG...'),
  ('products','no_products','No products found'),
  ('products','col_sku','SKU'),
  ('products','col_product','Product'),
  ('products','col_brand','Brand'),
  ('products','col_vitola','Vitola'),
  ('products','col_units_pack','Units/Pack'),
  ('products','col_role','Role'),
  ('products','role_original','Original'),
  ('products','role_aged','Aged'),
  ('products','role_sample','Sample'),
  ('products','role_foc','FOC'),
  ('products','filter_brands','Brands'),
  ('products','general_information','General Information'),
  ('products','product_details','Product Details'),
  -- inventory
  ('inventory','page_title','Inventory'),
  ('inventory','stock_movements','Stock Movements'),
  ('inventory','add_stock','Add Stock'),
  ('inventory','search_placeholder','Search SKU, product, brand...'),
  ('inventory','no_records','No inventory records'),
  ('inventory','col_sku','SKU'),
  ('inventory','col_product','Product'),
  ('inventory','col_brand','Brand'),
  ('inventory','col_total','Total'),
  ('inventory','select_product','Select a product...'),
  ('inventory','label_packs','Packs'),
  ('inventory','label_units','Units'),
  ('inventory','label_warehouse','Warehouse'),
  -- finance
  ('finance','expenses_title','Expenses'),
  ('finance','new_expense','New Expense'),
  ('finance','tab_all_expenses','All Expenses'),
  ('finance','tab_claims','Expense Claims'),
  ('finance','no_expenses','No expenses found'),
  ('finance','to_reimburse','To reimburse'),
  ('finance','mark_as_paid','Mark as Paid'),
  ('finance','col_date','Date'),
  ('finance','col_vendor','Vendor'),
  ('finance','col_category','Category'),
  ('finance','col_amount','Amount'),
  ('finance','col_receipt','Receipt'),
  ('finance','scan_receipt','Scan Receipt'),
  ('finance','field_date','Date'),
  ('finance','field_category','Category'),
  ('finance','field_vendor','Vendor / Payee'),
  ('finance','field_description','Description'),
  ('finance','field_amount','Amount'),
  ('finance','field_payment_method','Payment Method'),
  ('finance','add_expense','Add Expense'),
  ('finance','status_pending','Pending'),
  ('finance','status_approved','Approved'),
  ('finance','status_posted','Posted'),
  ('finance','status_rejected','Rejected'),
  ('finance','status_paid','Paid'),
  ('finance','status_submitted','Submitted'),
  ('finance','cat_office','Office & Admin'),
  ('finance','cat_travel','Travel & Entertainment'),
  ('finance','cat_meals','Meals & Beverages'),
  ('finance','cat_utilities','Utilities'),
  ('finance','cat_professional','Professional Fees'),
  ('finance','cat_marketing','Marketing & Events'),
  ('finance','cat_rent','Rent'),
  ('finance','cat_bank_charges','Bank Charges'),
  ('finance','cat_freight','Freight & Logistics'),
  ('finance','cat_other','Other'),
  -- retailers
  ('retailers','page_title','Retailers & Contacts'),
  ('retailers','add_retailer','Add retailer'),
  ('retailers','add_contact','Add contact'),
  ('retailers','tab_retailers','Retailers'),
  ('retailers','tab_b2c','B2C Contacts'),
  ('retailers','tab_map','Map'),
  ('retailers','search_placeholder','Search by shop, city, country...'),
  ('retailers','no_retailers','No retailers yet'),
  ('retailers','no_b2c','No B2C contacts yet — add people you meet at events'),
  ('retailers','form_add_title','Add Retailer'),
  ('retailers','form_edit_title','Edit Retailer'),
  ('retailers','retailer_name','Retailer Name'),
  ('retailers','retailer_information','Retailer Information'),
  ('retailers','photos_section','Photos'),
  ('retailers','add_photo','Add photo'),
  ('retailers','no_photos','No photos yet'),
  ('retailers','visit_notes_placeholder','Visit notes, product preferences...'),
  ('retailers','add_b2c_title','Add B2C Contact'),
  ('retailers','edit_b2c_title','Edit Contact'),
  ('retailers','linked_retailer','Linked Retailer'),
  ('retailers','event_occasion','Event / Occasion'),
  ('retailers','b2c_col_name','Name'),
  ('retailers','b2c_col_country','Country'),
  ('retailers','b2c_col_contact','Contact'),
  ('retailers','b2c_col_event','Event'),
  ('retailers','b2c_col_retailer','Retailer'),
  -- partners
  ('partners','page_title','Partners'),
  ('partners','add_partner','Add Partner'),
  ('partners','search_placeholder','Search name, contact, country...'),
  ('partners','no_partners','No partners found'),
  ('partners','filter_all_types','All Types'),
  ('partners','type_supplier','Supplier'),
  ('partners','type_agent','Agent'),
  ('partners','type_broker','Broker'),
  ('partners','col_name','Name'),
  ('partners','col_type','Type'),
  ('partners','col_contact','Contact'),
  ('partners','col_country','Country'),
  ('partners','col_payment_terms','Payment Terms'),
  ('partners','col_status','Status'),
  ('partners','general_information','General Information'),
  ('partners','commercial_terms','Commercial Terms'),
  -- price_lists
  ('price_lists','page_title','Price Lists'),
  ('price_lists','search_placeholder','Search SKU or product...'),
  ('price_lists','no_entries','No price entries found'),
  ('price_lists','col_sku','SKU'),
  ('price_lists','col_product','Product'),
  ('price_lists','edit_hint','Tap any price field to edit · Save button appears when a value is changed'),
  -- documents
  ('documents','page_title','Documents'),
  ('documents','add_external','Add External Document'),
  ('documents','file_label','File name / Label'),
  ('documents','no_folders','No folders match your search.'),
  ('documents','no_documents','No documents yet.'),
  ('documents','total_folders','Total Folders'),
  ('documents','total_files','Total Files'),
  -- reports
  ('reports','page_title','Reports'),
  ('reports','tab_overview','Overview'),
  ('reports','tab_geography','Geography'),
  ('reports','tab_products','Products'),
  ('reports','tab_clients','Clients'),
  ('reports','tab_activity','Activity'),
  ('reports','kpi_revenue','Revenue'),
  ('reports','kpi_units_shipped','Units shipped'),
  ('reports','kpi_active_clients','Active clients'),
  ('reports','col_region','Region'),
  ('reports','col_clients','Clients'),
  ('reports','col_revenue','Revenue'),
  ('reports','col_units','Units'),
  ('reports','col_orders','Orders'),
  ('reports','health_active','Active'),
  ('reports','health_at_risk','At risk'),
  ('reports','health_dormant','Dormant'),
  ('reports','health_lost','Lost'),
  ('reports','never_ordered','Never ordered'),
  -- targets
  ('targets','page_title','Financial Targets'),
  ('targets','subtitle','Set annual objectives per distributor'),
  ('targets','col_distributor','Distributor'),
  ('targets','col_standard','Standard ($)'),
  ('targets','col_push','Push ($)'),
  ('targets','col_stretch','Stretch ($)'),
  ('targets','col_progress','Progress'),
  ('targets','no_target','No target'),
  ('targets','status_urgent','Urgent'),
  ('targets','status_late','Late'),
  ('targets','status_good','Good'),
  ('targets','status_excellent','Excellent'),
  ('targets','status_amazing','Amazing'),
  -- tracking
  ('tracking','page_title','Tracking Log'),
  ('tracking','subtitle','Complete audit trail — who did what and when'),
  ('tracking','search_placeholder','Search user, document, action...'),
  ('tracking','no_events','No events found'),
  ('tracking','stat_today','Events today'),
  ('tracking','stat_users','Active users'),
  ('tracking','stat_admin','Admin actions'),
  ('tracking','stat_client','Client actions'),
  -- settings
  ('settings','page_title','Settings'),
  ('settings','language_title','Interface Language'),
  ('settings','language_description','Choose your display language. This preference is saved to your profile.'),
  ('settings','language_saved','Language updated'),
  -- cms
  ('cms','page_title','Content Management'),
  ('cms','labels_count','labels across namespaces'),
  ('cms','new_label','New label'),
  ('cms','col_key','Key'),
  ('cms','col_description','Description'),
  ('cms','col_translation','Translation'),
  ('cms','col_status','Status'),
  ('cms','no_labels','No labels in this namespace'),
  ('cms','no_translation_placeholder','No translation...'),
  ('cms','auto_translate','Auto-translate'),
  ('cms','translated_result','label(s) auto-translated'),
  ('cms','create','Create'),
  ('cms','label_namespace','Namespace'),
  ('cms','label_key','Key'),
  ('cms','label_description','Description')
) AS v(ns, k, val) ON l.namespace = v.ns AND l.key = v.k
ON CONFLICT (label_id, lang_code) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

-- Confirm counts
SELECT namespace, COUNT(*) as label_count FROM cms_labels GROUP BY namespace ORDER BY namespace;
